//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Objects;
    using System.Data.Objects.DataClasses;
    using System.Linq;
    
    public partial class ControlAsistenciaEntities : DbContext
    {
        public ControlAsistenciaEntities()
            : base("name=ControlAsistenciaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
    
        public virtual ObjectResult<procObtenerCalendarioAcademico_Result> procObtenerCalendarioAcademico()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<procObtenerCalendarioAcademico_Result>("procObtenerCalendarioAcademico");
        }
    }
}
